### ISSUE TITLE
Remove Terms and Conditions link from footer to fix resizing issue

### ISSUE THREAD

**Issue by r-southworth** [datagrove/datagrove-main#14]
![image](https://user-images.githubusercontent.com/105446541/189421503-7def35df-5bd5-421c-84c8-035f0344394a.png)

When you resize the browser window at certain sizes it does this - probably because we aren't using the normal Vite footer. Suggest we use the native footer and move the link for terms and conditions someplace else.

**Comment by meagan13** [comment]
Removed the Footer component and replaced with the built-in VitePress footer feature
