### ISSUE TITLE
Switch Header Logo to Fewer Bars Version

### ISSUE THREAD

**Issue by r-southworth** [datagrove/datagrove-main#4]
Logo in header should be one of the fewer bar versions, whichever looks better but should still be a circle logo
<img width="239" alt="Screen Shot 2022-07-01 at 10 19 14 AM" src="https://user-images.githubusercontent.com/105446541/176912344-4e25dd34-8046-44be-9333-b61dfb238073.png">

- [ ] Prepare PNG file 
- [ ] Add to [public folder](https://github.com/datagrove/datagrove-main/tree/main/docs/public)
- [ ] Change PNG path in [config.js file](https://github.com/datagrove/datagrove-main/blob/main/docs/.vitepress/config.js)

**Comment by meagan13** [comment]
Updated the favicon logo and the logo in the navbar to the five large bars circle
